import { XubioBaseRepository } from "./XubioBaseRepository.js";
import { 
  IFacturaCompraRepository, IOrdenCompraRepository, IDepositoRepository, IPagoRepository, IBancoRepository, ICuentaContableRepository, 
  IPresupuestoRepository, IRemitoRepository, IVendedorRepository, IPuntoVentaRepository,
  IMonedaRepository, IPaisRepository, IProvinciaRepository, ILocalidadRepository, ITasaIvaRepository, IActividadEconomicaRepository, IUnidadMedidaRepository,
  IAsientoManualRepository, IAjusteStockRepository, ICentroDeCostoRepository, IListaPrecioRepository, ICategoriaCuentaRepository, ICategoriaFiscalRepository, ICircuitoContableRepository, IIdentificacionTributariaRepository,
  IMiEmpresaRepository, IPercepcionRepository, IRetencionRepository, ISucursalRepository, ITransporteRepository, ITalonarioRepository, ITalonarioCobranzaRepository, IUnidadMedidaFinalRepository, IProductoCompraRepository, IRelacionComprobanteRepository, IComprobantesAsociadosRepository, IPDFRepository
} from "../../domain/repositories/IBatchRepositories.js";
import { FacturaCompra } from "../../domain/entities/FacturaCompra.js";
import { OrdenCompra } from "../../domain/entities/OrdenCompra.js";
import { Deposito } from "../../domain/entities/Deposito.js";
import { Pago } from "../../domain/entities/Pago.js";
import { Banco } from "../../domain/entities/Banco.js";
import { CuentaContable } from "../../domain/entities/CuentaContable.js";
import { Presupuesto } from "../../domain/entities/Presupuesto.js";
import { Remito } from "../../domain/entities/Remito.js";
import { Vendedor } from "../../domain/entities/Vendedor.js";
import { PuntoVenta } from "../../domain/entities/PuntoVenta.js";
import { Moneda, Pais, Provincia, Localidad, TasaIva, ActividadEconomica, UnidadMedida } from "../../domain/entities/ConfigEntities.js";
import { AsientoManual, AjusteStock, CentroDeCosto, ListaPrecio, CategoriaCuenta, CategoriaFiscal, CircuitoContable, IdentificacionTributaria } from "../../domain/entities/AccountingEntities.js";
import { MiEmpresa, Percepcion, Retencion, Sucursal, Transporte, Talonario, UnidadMedidaFinal, ProductoCompra, RelacionComprobante } from "../../domain/entities/MiscEntities.js";

export class XubioFacturaCompraRepository extends XubioBaseRepository implements IFacturaCompraRepository { async findAll(params?: any) { return await this.get("comprobanteCompraBean", params); } async findById(id: string | number) { return await this.getById("comprobanteCompraBean", id); } }
export class XubioOrdenCompraRepository extends XubioBaseRepository implements IOrdenCompraRepository { async findAll(params?: any) { return await this.get("ordenCompraBean", params); } async findById(id: string | number) { return await this.getById("ordenCompraBean", id); } }
export class XubioDepositoRepository extends XubioBaseRepository implements IDepositoRepository { async findAll(params?: any) { return await this.get("depositos", params); } async findById(id: string | number) { return await this.getById("depositos", id); } }
export class XubioPagoRepository extends XubioBaseRepository implements IPagoRepository { async findAll(params?: any) { return await this.get("pagoBean", params); } async findById(id: string | number) { return await this.getById("pagoBean", id); } }
export class XubioBancoRepository extends XubioBaseRepository implements IBancoRepository { async findAll(params?: any) { return await this.get("banco", params); } async findById(id: string | number) { return await this.getById("banco", id); } }
export class XubioCuentaContableRepository extends XubioBaseRepository implements ICuentaContableRepository { async findAll(params?: any) { return await this.get("cuenta", params); } async findById(id: string | number) { return await this.getById("cuenta", id); } }
export class XubioPresupuestoRepository extends XubioBaseRepository implements IPresupuestoRepository { async findAll(params?: any) { return await this.get("presupuestoBean", params); } async findById(id: string | number) { return await this.getById("presupuestoBean", id); } }
export class XubioRemitoRepository extends XubioBaseRepository implements IRemitoRepository { async findAll(params?: any) { return await this.get("remitoVentaBean", params); } async findById(id: string | number) { return await this.getById("remitoVentaBean", id); } }
export class XubioVendedorRepository extends XubioBaseRepository implements IVendedorRepository { async findAll(params?: any) { return await this.get("vendedorBean", params); } async findById(id: string | number) { return await this.getById("vendedorBean", id); } }
export class XubioPuntoVentaRepository extends XubioBaseRepository implements IPuntoVentaRepository { async findAll(params?: any) { return await this.get("puntoVentaBean", params); } async findById(id: string | number) { return await this.getById("puntoVentaBean", id); } }
export class XubioMonedaRepository extends XubioBaseRepository implements IMonedaRepository { async findAll(params?: any) { return await this.get("monedaBean", params); } async findById(id: string | number) { return await this.getById("monedaBean", id); } }
export class XubioPaisRepository extends XubioBaseRepository implements IPaisRepository { async findAll(params?: any) { return await this.get("paisBean", params); } async findById(id: string | number) { return await this.getById("paisBean", id); } }
export class XubioProvinciaRepository extends XubioBaseRepository implements IProvinciaRepository { async findAll(params?: any) { return await this.get("provinciaBean", params); } async findById(id: string | number) { return await this.getById("provinciaBean", id); } }
export class XubioLocalidadRepository extends XubioBaseRepository implements ILocalidadRepository { async findAll(params?: any) { return await this.get("localidadBean", params); } async findById(id: string | number) { return await this.getById("localidadBean", id); } }
export class XubioTasaIvaRepository extends XubioBaseRepository implements ITasaIvaRepository { async findAll(params?: any) { return await this.get("tasaImpositiva", params); } async findById(id: string | number) { return await this.getById("tasaImpositiva", id); } }
export class XubioActividadEconomicaRepository extends XubioBaseRepository implements IActividadEconomicaRepository { async findAll(params?: any) { return await this.get("actividadEconomicaBean", params); } async findById(id: string | number) { return await this.getById("actividadEconomicaBean", id); } }
export class XubioUnidadMedidaRepository extends XubioBaseRepository implements IUnidadMedidaRepository { async findAll(params?: any) { return await this.get("unidadMedidaBean", params); } async findById(id: string | number) { return await this.getById("unidadMedidaBean", id); } }
export class XubioAsientoManualRepository extends XubioBaseRepository implements IAsientoManualRepository { async findAll(params?: any) { return await this.get("asientoContableManualBean", params); } async findById(id: string | number) { return await this.getById("asientoContableManualBean", id); } }
export class XubioAjusteStockRepository extends XubioBaseRepository implements IAjusteStockRepository { async findAll(params?: any) { return await this.get("ajusteStockBean", params); } async findById(id: string | number) { return await this.getById("ajusteStockBean", id); } }
export class XubioCentroDeCostoRepository extends XubioBaseRepository implements ICentroDeCostoRepository { async findAll(params?: any) { return await this.get("centroDeCostoBean", params); } async findById(id: string | number) { return await this.getById("centroDeCostoBean", id); } }
export class XubioListaPrecioRepository extends XubioBaseRepository implements IListaPrecioRepository { async findAll(params?: any) { return await this.get("listaPrecioBean", params); } async findById(id: string | number) { return await this.getById("listaPrecioBean", id); } }
export class XubioCategoriaCuentaRepository extends XubioBaseRepository implements ICategoriaCuentaRepository { async findAll(params?: any) { return await this.get("categoriaCuenta", params); } async findById(id: string | number) { return await this.getById("categoriaCuenta", id); } }
export class XubioCategoriaFiscalRepository extends XubioBaseRepository implements ICategoriaFiscalRepository { async findAll(params?: any) { return await this.get("categoriaFiscal", params); } async findById(id: string | number) { return await this.getById("categoriaFiscal", id); } }
export class XubioCircuitoContableRepository extends XubioBaseRepository implements ICircuitoContableRepository { async findAll(params?: any) { return await this.get("circuitoContableBean", params); } async findById(id: string | number) { return await this.getById("circuitoContableBean", id); } }
export class XubioIdentificacionTributariaRepository extends XubioBaseRepository implements IIdentificacionTributariaRepository { async findAll(params?: any) { return await this.get("identificacionTributaria", params); } async findById(id: string | number) { return await this.getById("identificacionTributaria", id); } }

export class XubioMiEmpresaRepository extends XubioBaseRepository implements IMiEmpresaRepository { async findAll(params?: any) { return await this.get("miempresa", params); } async findById(id: string | number) { return await this.getById("miempresa", id); } }
export class XubioPercepcionRepository extends XubioBaseRepository implements IPercepcionRepository { async findAll(params?: any) { return await this.get("percepcionBean", params); } async findById(id: string | number) { return await this.getById("percepcionBean", id); } }
export class XubioRetencionRepository extends XubioBaseRepository implements IRetencionRepository { async findAll(params?: any) { return await this.get("retencionBean", params); } async findById(id: string | number) { return await this.getById("retencionBean", id); } }
export class XubioSucursalRepository extends XubioBaseRepository implements ISucursalRepository { async findAll(params?: any) { return await this.get("sucursalClienteBean", params); } async findById(id: string | number) { return await this.getById("sucursalClienteBean", id); } }
export class XubioTransporteRepository extends XubioBaseRepository implements ITransporteRepository { async findAll(params?: any) { return await this.get("transporteBean", params); } async findById(id: string | number) { return await this.getById("transporteBean", id); } }
export class XubioTalonarioRepository extends XubioBaseRepository implements ITalonarioRepository { async findAll(params?: any) { return await this.get("talonario", params); } async findById(id: string | number) { return await this.getById("talonario", id); } }
export class XubioTalonarioCobranzaRepository extends XubioBaseRepository implements ITalonarioCobranzaRepository { async findAll(params?: any) { return await this.get("talonarioCobranza", params); } async findById(id: string | number) { return await this.getById("talonarioCobranza", id); } }
export class XubioUnidadMedidaFinalRepository extends XubioBaseRepository implements IUnidadMedidaFinalRepository { async findAll(params?: any) { return await this.get("unidadMedida", params); } async findById(id: string | number) { return await this.getById("unidadMedida", id); } }
export class XubioProductoCompraRepository extends XubioBaseRepository implements IProductoCompraRepository { async findAll(params?: any) { return await this.get("ProductoCompraBean", params); } async findById(id: string | number) { return await this.getById("ProductoCompraBean", id); } }
export class XubioRelacionComprobanteRepository extends XubioBaseRepository implements IRelacionComprobanteRepository { async findAll(params?: any) { return await this.get("relacionFacturaNotaDeCredito", params); } async findById(id: string | number) { return await this.getById("relacionFacturaNotaDeCredito", id); } }
export class XubioComprobantesAsociadosRepository extends XubioBaseRepository implements IComprobantesAsociadosRepository { async findAll(params?: any) { return await this.get("comprobantesAsociados", params); } async findById(id: string | number) { return await this.getById("comprobantesAsociados", id); } }
export class XubioPDFRepository extends XubioBaseRepository implements IPDFRepository { async findAll(params?: any) { return await this.get("imprimirPDF", params); } async findById(id: string | number) { return await this.getById("imprimirPDF", id); } }
